{
 "title": "Logging Dashboard via Loki",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "Docker"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": {}
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)", "query": "200 OK" }
  ]
 },
 "panels": [
  {
   "title": "Total Logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"$container\", stream=~\"$stream\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Logs Per Stream",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"$container\"})[$__interval])) by (stream)",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Matching Logs",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"$container\", stream=~\"$stream\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Matching Logs Per Stream",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"$container\", stream=~\"$stream\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (stream)",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Matching Logs Percentage Per Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"$container\", stream=~\"$stream\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({container=\"$container\", stream=~\"$stream\"})[$__interval]))\n"
    }
   ]
  },
  {
   "title": "Match Word: \"$searchable_pattern\"",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{container=\"$container\", stream=~\"$stream\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  {
   "title": "Total count of stderr / stdout Historical",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"$container\"})[$__interval])) by (stream) != 0\n",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" historical",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=\"$container\"}|~ \"(?i)$searchable_pattern\")[$__interval])) by (stream) != 0",
     "legendFormat": "{{stream}}"
    }
   ]
  }
 ]
}