classDiagram
superduperdb-base-config-Api --|> superduperdb-base-jsonable-JSONable
superduperdb-base-config-Apis --|> superduperdb-base-jsonable-JSONable
superduperdb-base-config-Config --|> superduperdb-base-jsonable-JSONable
superduperdb-base-config-Config-Config --|> superduperdb-base-jsonable-JSONable-Config
superduperdb-base-config-Dask --|> superduperdb-base-config-IpPort
superduperdb-base-config-DataLayer --|> superduperdb-base-jsonable-JSONable
superduperdb-base-config-DataLayers --|> superduperdb-base-jsonable-JSONable
superduperdb-base-config-Deployment --|> superduperdb-base-jsonable-JSONable
superduperdb-base-config-HasPort --|> superduperdb-base-jsonable-JSONable
superduperdb-base-config-HostPort --|> superduperdb-base-config-HasPort
superduperdb-base-config-InMemory --|> superduperdb-base-jsonable-JSONable
superduperdb-base-config-IpPort --|> superduperdb-base-config-HasPort
superduperdb-base-config-LanceDB --|> superduperdb-base-jsonable-JSONable
superduperdb-base-config-LogLevel --|> enum-Enum
superduperdb-base-config-LogType --|> enum-Enum
superduperdb-base-config-Logging --|> superduperdb-base-jsonable-JSONable
superduperdb-base-config-ModelServer --|> superduperdb-base-config-HostPort
superduperdb-base-config-MongoDB --|> superduperdb-base-config-HostPort
superduperdb-base-config-Notebook --|> superduperdb-base-jsonable-JSONable
superduperdb-base-config-Retry --|> superduperdb-base-jsonable-JSONable
superduperdb-base-config-Server --|> superduperdb-base-jsonable-JSONable
superduperdb-base-config-VectorSearch --|> superduperdb-base-jsonable-JSONable
superduperdb-container-artifact-ArtifactDesc --|> typing-TypedDict
superduperdb-container-component-Component --|> superduperdb-container-serializable-Serializable
superduperdb-container-dataset-Dataset --|> superduperdb-container-component-Component
superduperdb-container-encoder-Encoder --|> superduperdb-container-component-Component
superduperdb-container-job-ComponentJob --|> superduperdb-container-job-Job
superduperdb-container-job-FunctionJob --|> superduperdb-container-job-Job
superduperdb-container-listener-Listener --|> superduperdb-container-component-Component
superduperdb-container-metric-Metric --|> superduperdb-container-component-Component
superduperdb-container-model-Model --|> superduperdb-container-component-Component
superduperdb-container-model-Model --|> superduperdb-container-model-PredictMixin
superduperdb-container-model-_TrainingConfiguration --|> superduperdb-container-component-Component
superduperdb-container-vector_index-VectorIndex --|> superduperdb-container-component-Component
superduperdb-data-cache-key_cache-Cache --|> abc-ABC
superduperdb-data-cache-key_cache-KeyCache --|> superduperdb-data-cache-key_cache-Cache
superduperdb-data-cache-key_cache-KeyCache --|> typing-Generic
superduperdb-data-cache-uri_cache-Cached --|> typing-Generic
superduperdb-data-cache-uri_cache-URICache --|> superduperdb-data-cache-typed_cache-TypedCache
superduperdb-db-base-artifact-ArtifactStore --|> abc-ABC
superduperdb-db-base-cdc-DatabaseListenerFactory --|> typing-Generic
superduperdb-db-base-data_backend-BaseDataBackend --|> abc-ABC
superduperdb-db-base-download-Downloader --|> superduperdb-db-base-download-BaseDownloader
superduperdb-db-base-download-InMemoryDownloader --|> superduperdb-db-base-download-BaseDownloader
superduperdb-db-base-metadata-MetaDataStore --|> abc-ABC
superduperdb-db-base-query-Delete --|> abc-ABC
superduperdb-db-base-query-Delete --|> superduperdb-container-serializable-Serializable
superduperdb-db-base-query-Insert --|> abc-ABC
superduperdb-db-base-query-Insert --|> superduperdb-container-serializable-Serializable
superduperdb-db-base-query-Like --|> abc-ABC
superduperdb-db-base-query-Like --|> superduperdb-container-serializable-Serializable
superduperdb-db-base-query-Select --|> abc-ABC
superduperdb-db-base-query-Select --|> superduperdb-container-serializable-Serializable
superduperdb-db-base-query-SelectOne --|> abc-ABC
superduperdb-db-base-query-SelectOne --|> superduperdb-container-serializable-Serializable
superduperdb-db-base-query-Update --|> abc-ABC
superduperdb-db-base-query-Update --|> superduperdb-container-serializable-Serializable
superduperdb-db-mongodb-artifacts-MongoArtifactStore --|> superduperdb-db-base-artifact-ArtifactStore
superduperdb-db-mongodb-cdc-BaseDatabaseListener --|> abc-ABC
superduperdb-db-mongodb-cdc-CDCHandler --|> threading-Thread
superduperdb-db-mongodb-cdc-CDCKeys --|> enum-Enum
superduperdb-db-mongodb-cdc-DBEvent --|> enum-Enum
superduperdb-db-mongodb-cdc-MongoDatabaseListener --|> superduperdb-db-mongodb-cdc-BaseDatabaseListener
superduperdb-db-mongodb-cdc-MongoDatabaseListener --|> superduperdb-db-mongodb-cdc-MongoEventMixin
superduperdb-db-mongodb-cdc-ObjectId --|> bson-objectid-ObjectId
superduperdb-db-mongodb-cdc-_DatabaseListenerThreadScheduler --|> threading-Thread
superduperdb-db-mongodb-data_backend-MongoDataBackend --|> superduperdb-db-base-data_backend-BaseDataBackend
superduperdb-db-mongodb-loading-MongoIterable --|> torch-utils-data-dataset-IterableDataset
superduperdb-db-mongodb-metadata-MongoMetaDataStore --|> superduperdb-db-base-metadata-MetaDataStore
superduperdb-db-mongodb-query-Aggregate --|> superduperdb-db-base-query-Select
superduperdb-db-mongodb-query-Collection --|> superduperdb-container-serializable-Serializable
superduperdb-db-mongodb-query-Count --|> superduperdb-db-base-query-SelectOne
superduperdb-db-mongodb-query-CountDocuments --|> superduperdb-db-mongodb-query-Find
superduperdb-db-mongodb-query-DeleteMany --|> superduperdb-db-base-query-Delete
superduperdb-db-mongodb-query-DeleteOne --|> superduperdb-db-base-query-Delete
superduperdb-db-mongodb-query-Featurize --|> superduperdb-db-base-query-Select
superduperdb-db-mongodb-query-FeaturizeOne --|> superduperdb-db-base-query-SelectOne
superduperdb-db-mongodb-query-Find --|> superduperdb-db-base-query-Select
superduperdb-db-mongodb-query-FindOne --|> superduperdb-db-base-query-SelectOne
superduperdb-db-mongodb-query-InsertMany --|> superduperdb-db-base-query-Insert
superduperdb-db-mongodb-query-Limit --|> superduperdb-db-base-query-Select
superduperdb-db-mongodb-query-PostLike --|> superduperdb-db-base-query-Select
superduperdb-db-mongodb-query-PreLike --|> superduperdb-db-base-query-Like
superduperdb-db-mongodb-query-ReplaceOne --|> superduperdb-db-base-query-Update
superduperdb-db-mongodb-query-UpdateMany --|> superduperdb-db-base-query-Update
superduperdb-db-mongodb-query-UpdateOne --|> superduperdb-db-base-query-Update
superduperdb-db-query_dataset-CachedQueryDataset --|> torch-utils-data-dataset-Dataset
superduperdb-db-query_dataset-QueryDataset --|> torch-utils-data-dataset-Dataset
superduperdb-ext-openai-model-OpenAI --|> superduperdb-container-component-Component
superduperdb-ext-openai-model-OpenAI --|> superduperdb-container-model-PredictMixin
superduperdb-ext-openai-model-OpenAIChatCompletion --|> superduperdb-ext-openai-model-OpenAI
superduperdb-ext-openai-model-OpenAIEmbedding --|> superduperdb-ext-openai-model-OpenAI
superduperdb-ext-sklearn-model-Estimator --|> superduperdb-container-model-Model
superduperdb-ext-sklearn-model-SklearnTrainingConfiguration --|> superduperdb-container-model-_TrainingConfiguration
superduperdb-ext-torch-model-BasicDataset --|> torch-utils-data-dataset-Dataset
superduperdb-ext-torch-model-TorchModel --|> superduperdb-container-model-Model
superduperdb-ext-torch-model-TorchModel --|> superduperdb-ext-torch-model-Base
superduperdb-ext-torch-model-TorchTrainerConfiguration --|> superduperdb-container-model-_TrainingConfiguration
superduperdb-ext-transformers-model-Pipeline --|> superduperdb-container-model-Model
superduperdb-misc-serialization-DillSerializer --|> superduperdb-misc-serialization-Serializer
superduperdb-misc-serialization-ModuleClassDict --|> typing-TypedDict
superduperdb-misc-serialization-PickleSerializer --|> superduperdb-misc-serialization-Serializer
superduperdb-misc-serialization-Serializer --|> abc-ABC
superduperdb-misc-serialization-TorchSerializer --|> superduperdb-misc-serialization-Serializer
superduperdb-misc-superduper-MongoDbTyper --|> superduperdb-misc-superduper-DuckTyper
superduperdb-misc-superduper-SklearnTyper --|> superduperdb-misc-superduper-DuckTyper
superduperdb-misc-superduper-TorchTyper --|> superduperdb-misc-superduper-DuckTyper
superduperdb-vector_search-base-VectorCollection --|> abc-ABC
superduperdb-vector_search-base-VectorDatabase --|> abc-ABC
superduperdb-vector_search-faiss_index-FaissVectorIndex --|> superduperdb-vector_search-base-BaseVectorIndex
superduperdb-vector_search-inmemory-InMemoryVectorCollection --|> superduperdb-vector_search-base-VectorCollection
superduperdb-vector_search-inmemory-InMemoryVectorDatabase --|> superduperdb-vector_search-base-VectorDatabase
superduperdb-vector_search-lancedb_client-LanceVectorIndex --|> superduperdb-vector_search-base-BaseVectorIndex
superduperdb-vector_search-table_scan-VanillaVectorIndex --|> superduperdb-vector_search-base-BaseVectorIndex
torch-utils-data-dataset-Dataset --|> typing-Generic
torch-utils-data-dataset-IterableDataset --|> torch-utils-data-dataset-Dataset
superduperdb-base-config-Apis --* superduperdb-base-config-Config
superduperdb-base-config-Dask --* superduperdb-base-config-Config
superduperdb-base-config-DataLayer --* superduperdb-base-config-DataLayers
superduperdb-base-config-DataLayer --* superduperdb-base-config-DataLayers
superduperdb-base-config-DataLayer --* superduperdb-base-config-DataLayers
superduperdb-base-config-DataLayers --* superduperdb-base-config-Config
superduperdb-base-config-LogLevel --* superduperdb-base-config-Logging
superduperdb-base-config-LogType --* superduperdb-base-config-Logging
superduperdb-base-config-Logging --* superduperdb-base-config-Config
superduperdb-base-config-ModelServer --* superduperdb-base-config-Config
superduperdb-base-config-Notebook --* superduperdb-base-config-Config
superduperdb-base-config-Retry --* superduperdb-base-config-Apis
superduperdb-base-config-Retry --* superduperdb-misc-retry-Retry
superduperdb-base-config-Server --* superduperdb-base-config-Config
superduperdb-base-config-VectorSearch --* superduperdb-base-config-Config
superduperdb-container-artifact-Artifact --* superduperdb-ext-torch-model-TorchTrainerConfiguration
superduperdb-container-artifact-Artifact --* superduperdb-ext-transformers-model-Pipeline
superduperdb-container-artifact-Artifact --* superduperdb-ext-transformers-model-Pipeline
superduperdb-container-document-Document --* superduperdb-db-mongodb-query-PostLike
superduperdb-container-document-Document --* superduperdb-db-mongodb-query-PreLike
superduperdb-container-document-Document --* superduperdb-db-mongodb-query-ReplaceOne
superduperdb-container-document-Document --* superduperdb-db-mongodb-query-UpdateMany
superduperdb-container-document-Document --* superduperdb-db-mongodb-query-UpdateOne
superduperdb-container-encoder-Encoder --* superduperdb-ext-openai-model-OpenAIEmbedding
superduperdb-container-serializable-Serializable --* superduperdb-db-mongodb-cdc-Packet
superduperdb-db-base-db-DB --* superduperdb-container-task_workflow-TaskWorkflow
superduperdb-db-base-db-DB --* superduperdb-db-base-db-LoadDict
superduperdb-db-base-db-DB --* superduperdb-db-query_dataset-CachedQueryDataset
superduperdb-db-base-db-DB --* superduperdb-db-query_dataset-QueryDataset
superduperdb-db-base-db-LoadDict --* superduperdb-db-base-db-DB
superduperdb-db-base-db-LoadDict --* superduperdb-db-base-db-DB
superduperdb-db-base-db-LoadDict --* superduperdb-db-base-db-DB
superduperdb-db-base-db-LoadDict --* superduperdb-db-base-db-DB
superduperdb-db-base-download-Fetcher --* superduperdb-db-base-download-Downloader
superduperdb-db-base-download-Fetcher --* superduperdb-db-base-download-InMemoryDownloader
superduperdb-db-base-query-Select --* superduperdb-db-base-data_backend-BaseDataBackend
superduperdb-db-mongodb-cdc-CDCHandler --* superduperdb-db-mongodb-cdc-MongoDatabaseListener
superduperdb-db-mongodb-cdc-CachedTokens --* superduperdb-db-mongodb-cdc-MongoDatabaseListener
superduperdb-db-mongodb-query-Collection --* superduperdb-db-mongodb-query-Aggregate
superduperdb-db-mongodb-query-Collection --* superduperdb-db-mongodb-query-ChangeStream
superduperdb-db-mongodb-query-Collection --* superduperdb-db-mongodb-query-DeleteMany
superduperdb-db-mongodb-query-Collection --* superduperdb-db-mongodb-query-DeleteOne
superduperdb-db-mongodb-query-Collection --* superduperdb-db-mongodb-query-InsertMany
superduperdb-db-mongodb-query-Collection --* superduperdb-db-mongodb-query-PreLike
superduperdb-db-mongodb-query-Collection --* superduperdb-db-mongodb-query-ReplaceOne
superduperdb-db-mongodb-query-Collection --* superduperdb-db-mongodb-query-UpdateMany
superduperdb-db-mongodb-query-Collection --* superduperdb-db-mongodb-query-UpdateOne
superduperdb-db-query_dataset-ExpiryCache --* superduperdb-db-query_dataset-CachedQueryDataset
superduperdb-db-query_dataset-ExpiryCache --* superduperdb-db-query_dataset-CachedQueryDataset
superduperdb-server-client-Client --* superduperdb-server-client-LoadDict
superduperdb-server-client-LoadDict --* superduperdb-server-client-Client
superduperdb-vector_search-lancedb_client-LanceDBClient --* superduperdb-vector_search-lancedb_client-LanceVectorIndex
superduperdb-vector_search-table_scan-VanillaVectorIndex --* superduperdb-vector_search-inmemory-InMemoryVectorCollection
superduperdb-db-base-artifact-ArtifactStore --o superduperdb-db-base-db-DB
superduperdb-db-base-data_backend-BaseDataBackend --o superduperdb-db-base-db-DB
superduperdb-db-base-db-DB --o superduperdb-db-mongodb-cdc-CDCHandler
superduperdb-db-base-db-DB --o superduperdb-db-mongodb-cdc-MongoDatabaseListener
superduperdb-db-base-metadata-MetaDataStore --o superduperdb-db-base-db-DB
superduperdb-db-mongodb-cdc-BaseDatabaseListener --o superduperdb-db-mongodb-cdc-_DatabaseListenerThreadScheduler
superduperdb-db-mongodb-query-Collection --o superduperdb-db-mongodb-cdc-MongoDatabaseListener
threading-Thread --o superduperdb-db-mongodb-cdc-MongoDatabaseListener
