classDiagram
superduperdb --> superduperdb-base
superduperdb --> superduperdb-misc-superduper
superduperdb-__main__ --> superduperdb-cli
superduperdb-__main__ --> superduperdb-cli-config
superduperdb-__main__ --> superduperdb-cli-docs
superduperdb-__main__ --> superduperdb-cli-info
superduperdb-__main__ --> superduperdb-cli-serve
superduperdb-base-config --> superduperdb-base-jsonable
superduperdb-base-configs --> superduperdb-base-config
superduperdb-base-logger --> superduperdb-base-configs
superduperdb-cli-config --> superduperdb
superduperdb-cli-docs --> superduperdb
superduperdb-cli-docs --> superduperdb-misc
superduperdb-cli-docs --> superduperdb-misc-run
superduperdb-cli-info --> superduperdb
superduperdb-cli-info --> superduperdb-misc
superduperdb-cli-info --> superduperdb-misc-run
superduperdb-cli-serve --> superduperdb
superduperdb-cli-serve --> superduperdb-db-base-build
superduperdb-cli-serve --> superduperdb-db-base-cdc
superduperdb-cli-serve --> superduperdb-db-mongodb-query
superduperdb-cli-serve --> superduperdb-server-dask_client
superduperdb-cli-serve --> superduperdb-server-server
superduperdb-container-artifact --> superduperdb-db-base-artifact
superduperdb-container-artifact --> superduperdb-misc-serialization
superduperdb-container-artifact_tree --> superduperdb-container-artifact
superduperdb-container-artifact_tree --> superduperdb-data-tree-tree
superduperdb-container-artifact_tree --> superduperdb-db-base-artifact
superduperdb-container-artifact_tree --> superduperdb-misc-serialization
superduperdb-container-component --> superduperdb-container-job
superduperdb-container-component --> superduperdb-container-serializable
superduperdb-container-component --> superduperdb-db-base
superduperdb-container-component --> superduperdb-db-base-db
superduperdb-container-dataset --> superduperdb-container-artifact
superduperdb-container-dataset --> superduperdb-container-component
superduperdb-container-dataset --> superduperdb-container-document
superduperdb-container-dataset --> superduperdb-db-base-db
superduperdb-container-dataset --> superduperdb-db-mongodb-query
superduperdb-container-document --> superduperdb
superduperdb-container-document --> superduperdb-container-encoder
superduperdb-container-encoder --> superduperdb-container-artifact
superduperdb-container-encoder --> superduperdb-container-component
superduperdb-container-encoder --> superduperdb-misc
superduperdb-container-encoder --> superduperdb-misc-dataclasses
superduperdb-container-job --> superduperdb
superduperdb-container-job --> superduperdb-container-tasks
superduperdb-container-job --> superduperdb-db-base-build
superduperdb-container-listener --> superduperdb-container-component
superduperdb-container-listener --> superduperdb-container-job
superduperdb-container-listener --> superduperdb-container-model
superduperdb-container-listener --> superduperdb-db-base-db
superduperdb-container-listener --> superduperdb-db-base-query
superduperdb-container-metric --> superduperdb-container-artifact
superduperdb-container-metric --> superduperdb-container-component
superduperdb-container-model --> superduperdb
superduperdb-container-model --> superduperdb-container-artifact
superduperdb-container-model --> superduperdb-container-component
superduperdb-container-model --> superduperdb-container-dataset
superduperdb-container-model --> superduperdb-container-encoder
superduperdb-container-model --> superduperdb-container-job
superduperdb-container-model --> superduperdb-container-listener
superduperdb-container-model --> superduperdb-container-metric
superduperdb-container-model --> superduperdb-container-serializable
superduperdb-container-model --> superduperdb-db-base-db
superduperdb-container-model --> superduperdb-db-base-query
superduperdb-container-model --> superduperdb-db-query_dataset
superduperdb-container-model --> superduperdb-misc-special_dicts
superduperdb-container-serializable --> superduperdb-container-component
superduperdb-container-task_workflow --> superduperdb
superduperdb-container-task_workflow --> superduperdb-container-job
superduperdb-container-task_workflow --> superduperdb-db-base-db
superduperdb-container-tasks --> superduperdb-db-base-build
superduperdb-container-vector_index --> superduperdb
superduperdb-container-vector_index --> superduperdb-container-component
superduperdb-container-vector_index --> superduperdb-container-document
superduperdb-container-vector_index --> superduperdb-container-encoder
superduperdb-container-vector_index --> superduperdb-container-listener
superduperdb-container-vector_index --> superduperdb-db-base-db
superduperdb-container-vector_index --> superduperdb-misc-special_dicts
superduperdb-container-vector_index --> superduperdb-vector_search-base
superduperdb-data-cache-typed_cache --> superduperdb-data-cache-key_cache
superduperdb-data-cache-uri_cache --> superduperdb-data-cache-typed_cache
superduperdb-data-cache-uri_cache --> superduperdb-data-tree-for_each
superduperdb-data-tree-for_each --> superduperdb
superduperdb-data-tree-for_each --> superduperdb-misc
superduperdb-data-tree-for_each --> superduperdb-misc-dataclasses
superduperdb-db-base-artifact --> superduperdb-misc-serialization
superduperdb-db-base-backends --> superduperdb-base
superduperdb-db-base-backends --> superduperdb-base-config
superduperdb-db-base-backends --> superduperdb-db-mongodb-artifacts
superduperdb-db-base-backends --> superduperdb-db-mongodb-data_backend
superduperdb-db-base-backends --> superduperdb-db-mongodb-metadata
superduperdb-db-base-backends --> superduperdb-vector_search-inmemory
superduperdb-db-base-backends --> superduperdb-vector_search-lancedb_client
superduperdb-db-base-build --> superduperdb
superduperdb-db-base-build --> superduperdb-db-base-backends
superduperdb-db-base-build --> superduperdb-db-base-db
superduperdb-db-base-build --> superduperdb-server-dask_client
superduperdb-db-base-cdc --> superduperdb-db-base
superduperdb-db-base-cdc --> superduperdb-db-base-backends
superduperdb-db-base-cdc --> superduperdb-db-base-db
superduperdb-db-base-cdc --> superduperdb-db-mongodb
superduperdb-db-base-cdc --> superduperdb-db-mongodb-cdc
superduperdb-db-base-cdc --> superduperdb-db-mongodb-query
superduperdb-db-base-cursor --> superduperdb-container-document
superduperdb-db-base-cursor --> superduperdb-container-encoder
superduperdb-db-base-cursor --> superduperdb-misc-special_dicts
superduperdb-db-base-data_backend --> superduperdb-container-document
superduperdb-db-base-data_backend --> superduperdb-container-model
superduperdb-db-base-data_backend --> superduperdb-db-base-query
superduperdb-db-base-db --> superduperdb
superduperdb-db-base-db --> superduperdb-container-artifact_tree
superduperdb-db-base-db --> superduperdb-container-component
superduperdb-db-base-db --> superduperdb-container-document
superduperdb-db-base-db --> superduperdb-container-job
superduperdb-db-base-db --> superduperdb-container-serializable
superduperdb-db-base-db --> superduperdb-container-task_workflow
superduperdb-db-base-db --> superduperdb-db-base-artifact
superduperdb-db-base-db --> superduperdb-db-base-data_backend
superduperdb-db-base-db --> superduperdb-db-base-download
superduperdb-db-base-db --> superduperdb-db-base-download_content
superduperdb-db-base-db --> superduperdb-db-base-exceptions
superduperdb-db-base-db --> superduperdb-db-base-metadata
superduperdb-db-base-db --> superduperdb-db-base-query
superduperdb-db-base-db --> superduperdb-misc-special_dicts
superduperdb-db-base-db --> superduperdb-vector_search-base
superduperdb-db-base-download --> superduperdb
superduperdb-db-base-download_content --> superduperdb
superduperdb-db-base-download_content --> superduperdb-container-document
superduperdb-db-base-download_content --> superduperdb-container-serializable
superduperdb-db-base-download_content --> superduperdb-db-base-download
superduperdb-db-base-download_content --> superduperdb-db-base-query
superduperdb-db-base-query --> superduperdb-container-model
superduperdb-db-base-query --> superduperdb-container-serializable
superduperdb-db-base-query --> superduperdb-db-base-db
superduperdb-db-mongodb-artifacts --> superduperdb-db-base-artifact
superduperdb-db-mongodb-cdc --> superduperdb
superduperdb-db-mongodb-cdc --> superduperdb-container-job
superduperdb-db-mongodb-cdc --> superduperdb-container-serializable
superduperdb-db-mongodb-cdc --> superduperdb-container-task_workflow
superduperdb-db-mongodb-cdc --> superduperdb-container-vector_index
superduperdb-db-mongodb-cdc --> superduperdb-db-base-db
superduperdb-db-mongodb-cdc --> superduperdb-db-mongodb
superduperdb-db-mongodb-cdc --> superduperdb-db-mongodb-query
superduperdb-db-mongodb-cdc --> superduperdb-misc-task_queue
superduperdb-db-mongodb-cdc --> superduperdb-vector_search-base
superduperdb-db-mongodb-data_backend --> superduperdb
superduperdb-db-mongodb-data_backend --> superduperdb-container-document
superduperdb-db-mongodb-data_backend --> superduperdb-container-serializable
superduperdb-db-mongodb-data_backend --> superduperdb-db-base-data_backend
superduperdb-db-mongodb-data_backend --> superduperdb-misc-special_dicts
superduperdb-db-mongodb-metadata --> superduperdb-container-component
superduperdb-db-mongodb-metadata --> superduperdb-db-base-metadata
superduperdb-db-mongodb-query --> superduperdb
superduperdb-db-mongodb-query --> superduperdb-container-document
superduperdb-db-mongodb-query --> superduperdb-container-model
superduperdb-db-mongodb-query --> superduperdb-container-serializable
superduperdb-db-mongodb-query --> superduperdb-db-base-db
superduperdb-db-query_dataset --> superduperdb-db-base-build
superduperdb-db-query_dataset --> superduperdb-db-base-query
superduperdb-db-query_dataset --> superduperdb-misc-special_dicts
superduperdb-ext-numpy-array --> superduperdb-container-encoder
superduperdb-ext-numpy-array --> superduperdb-ext-utils
superduperdb-ext-openai-model --> superduperdb
superduperdb-ext-openai-model --> superduperdb-container-component
superduperdb-ext-openai-model --> superduperdb-container-encoder
superduperdb-ext-openai-model --> superduperdb-container-model
superduperdb-ext-openai-model --> superduperdb-ext-vector-vectors-vector
superduperdb-ext-openai-model --> superduperdb-misc-compat
superduperdb-ext-openai-model --> superduperdb-misc-retry
superduperdb-ext-pillow-image --> superduperdb-container-encoder
superduperdb-ext-sklearn-model --> superduperdb-container-artifact
superduperdb-ext-sklearn-model --> superduperdb-container-metric
superduperdb-ext-sklearn-model --> superduperdb-container-model
superduperdb-ext-sklearn-model --> superduperdb-db-base-db
superduperdb-ext-sklearn-model --> superduperdb-db-base-query
superduperdb-ext-sklearn-model --> superduperdb-db-query_dataset
superduperdb-ext-torch-model --> superduperdb
superduperdb-ext-torch-model --> superduperdb-container-artifact
superduperdb-ext-torch-model --> superduperdb-container-document
superduperdb-ext-torch-model --> superduperdb-container-encoder
superduperdb-ext-torch-model --> superduperdb-container-metric
superduperdb-ext-torch-model --> superduperdb-container-model
superduperdb-ext-torch-model --> superduperdb-container-serializable
superduperdb-ext-torch-model --> superduperdb-db-base-db
superduperdb-ext-torch-model --> superduperdb-db-base-query
superduperdb-ext-torch-model --> superduperdb-db-query_dataset
superduperdb-ext-torch-model --> superduperdb-ext-torch-utils
superduperdb-ext-torch-tensor --> superduperdb-container-encoder
superduperdb-ext-torch-tensor --> superduperdb-ext-utils
superduperdb-ext-torch-utils --> superduperdb-ext-torch-model
superduperdb-ext-transformers-model --> superduperdb-container-artifact
superduperdb-ext-transformers-model --> superduperdb-container-metric
superduperdb-ext-transformers-model --> superduperdb-container-model
superduperdb-ext-transformers-model --> superduperdb-db-base-db
superduperdb-ext-transformers-model --> superduperdb-db-base-query
superduperdb-ext-transformers-model --> superduperdb-db-query_dataset
superduperdb-ext-transformers-model --> superduperdb-misc-special_dicts
superduperdb-ext-vector-vectors-vector --> superduperdb-container-encoder
superduperdb-ext-vector-vectors-vector --> superduperdb-ext-utils
superduperdb-misc-classification --> superduperdb-container-metric
superduperdb-misc-classification --> superduperdb-ext-torch-model
superduperdb-misc-dataclasses --> superduperdb-misc-dataclasses
superduperdb-misc-retry --> superduperdb
superduperdb-misc-retry --> superduperdb-misc-dataclasses
superduperdb-misc-run --> superduperdb
superduperdb-misc-serialization --> superduperdb-ext-torch-utils
superduperdb-misc-superduper --> superduperdb
superduperdb-misc-superduper --> superduperdb-db-base-build
superduperdb-misc-superduper --> superduperdb-db-base-db
superduperdb-misc-superduper --> superduperdb-db-mongodb-artifacts
superduperdb-misc-superduper --> superduperdb-db-mongodb-data_backend
superduperdb-misc-superduper --> superduperdb-db-mongodb-metadata
superduperdb-misc-superduper --> superduperdb-ext-sklearn-model
superduperdb-misc-superduper --> superduperdb-ext-torch-model
superduperdb-server-client --> superduperdb-container-artifact_tree
superduperdb-server-client --> superduperdb-container-component
superduperdb-server-client --> superduperdb-container-document
superduperdb-server-client --> superduperdb-container-serializable
superduperdb-server-client --> superduperdb-db-base-db
superduperdb-server-client --> superduperdb-db-base-query
superduperdb-server-client --> superduperdb-misc-serialization
superduperdb-server-dask_client --> superduperdb
superduperdb-server-login --> superduperdb
superduperdb-server-server --> superduperdb
superduperdb-server-server --> superduperdb-container-artifact_tree
superduperdb-server-server --> superduperdb-container-document
superduperdb-server-server --> superduperdb-container-serializable
superduperdb-server-server --> superduperdb-db-base-build
superduperdb-server-server --> superduperdb-misc-serialization
superduperdb-vector_search --> superduperdb-vector_search-faiss_index
superduperdb-vector_search --> superduperdb-vector_search-table_scan
superduperdb-vector_search-base --> superduperdb
superduperdb-vector_search-faiss_index --> superduperdb-vector_search-base
superduperdb-vector_search-inmemory --> superduperdb-vector_search-base
superduperdb-vector_search-inmemory --> superduperdb-vector_search-table_scan
superduperdb-vector_search-lancedb_client --> superduperdb
superduperdb-vector_search-lancedb_client --> superduperdb-vector_search-base
superduperdb-vector_search-lancedb_client --> superduperdb-vector_search-base
superduperdb-vector_search-table_scan --> superduperdb
superduperdb-vector_search-table_scan --> superduperdb-vector_search-base
